export { default as Faqs } from "./faqs";
export { HeroSection, HeroSectionMobile } from "./hero-section";
export { InstructorsSection, InstructorsSectionMobile } from "./instructors-section";
export { default as InvestorsSection } from "./investors-section";
export { LearningJourney, LearningJourneyMobile } from "./learning-journey";
export { MakeStuffSection, MakeStuffSectionMobile } from "./make-stuff-section";
export { default as NewCohortSection } from "./new-cohort-section";
export { OnlineCoursesSuckSection, OnlineCourseSuckSectionMobile } from "./online-courses-suck-section";
export { PricingSection, PricingSectionMobile } from "./pricing-section";
export { default as TestimonialsSection } from "./testimonials-section";
export { WhatBuild, WhatBuildMobile } from "./what-build";
export { WhatToExpectSection, WhatToExpectSectionMobile } from "./what-to-expect-section";
export { WhyCbcSection, WhyCbcSectionMobile } from "./why-cbc-section";
